package com.weddingraffle.rifa.service.impl;

enum PaymentReconciliationFailure {
    PAYMENT_ID_MISMATCH,
    TRANSACTION_NOT_FOUND,
    PAYMENT_METHOD_MISMATCH,
    PAYMENT_ID_ALREADY_LINKED,
    AMOUNT_MISMATCH,
    CURRENCY_MISMATCH,
    EXTERNAL_REFERENCE_MISMATCH,
    ORDER_EXTERNAL_REFERENCE_MISMATCH,
    PREFERENCE_ID_MISMATCH,
    COLLECTOR_ID_MISMATCH,
    MISSING_PROVIDER_TIMESTAMP,
    UNSUPPORTED_PROVIDER_STATUS
}
