import { getMercadoPagoDeviceId } from './mercadoPagoSecurity';

type MercadoPagoWindow = Window & { MP_DEVICE_SESSION_ID?: unknown };

describe('Mercado Pago security', () => {
  afterEach(() => {
    delete (window as MercadoPagoWindow).MP_DEVICE_SESSION_ID;
  });

  it('returns the Device ID generated by security.js', () => {
    (window as MercadoPagoWindow).MP_DEVICE_SESSION_ID = 'device-session-123';

    expect(getMercadoPagoDeviceId()).toBe('device-session-123');
  });

  it('ignores missing or invalid Device IDs', () => {
    expect(getMercadoPagoDeviceId()).toBeUndefined();

    (window as MercadoPagoWindow).MP_DEVICE_SESSION_ID = 'invalid\nvalue';
    expect(getMercadoPagoDeviceId()).toBeUndefined();
  });
});
