ALTER TABLE transaction
    ADD COLUMN capacity_review_status VARCHAR(40),
    ADD CONSTRAINT chk_transaction_capacity_review_status
        CHECK (capacity_review_status IN (
            'PENDING',
            'REFUND_COMPLETED',
            'CONTRIBUTION_WITHOUT_NUMBERS'
        ));

CREATE TABLE raffle_capacity (
    id SMALLINT PRIMARY KEY,
    total_capacity BIGINT NOT NULL CHECK (total_capacity > 0),
    reserved_quantity BIGINT NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    allocated_quantity BIGINT NOT NULL DEFAULT 0 CHECK (allocated_quantity >= 0),
    CONSTRAINT chk_raffle_capacity_singleton CHECK (id = 1),
    CONSTRAINT chk_raffle_capacity_limit
        CHECK (reserved_quantity + allocated_quantity <= total_capacity)
);

INSERT INTO raffle_capacity (id, total_capacity, allocated_quantity)
SELECT
    1,
    CAST('${raffle_number_max}' AS BIGINT) - CAST('${raffle_number_min}' AS BIGINT) + 1,
    COUNT(*)
FROM lucky_number;

CREATE TABLE capacity_reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_reference VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    status VARCHAR(30) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_capacity_reservation_external_reference UNIQUE (external_reference),
    CONSTRAINT chk_capacity_reservation_status
        CHECK (status IN ('ACTIVE', 'ALLOCATED', 'EXPIRED', 'RELEASED', 'CAPACITY_REJECTED'))
);

INSERT INTO capacity_reservation (external_reference, quantity, status, expires_at)
SELECT
    raffle_transaction.external_reference,
    COUNT(lucky_number.id),
    'ALLOCATED',
    raffle_transaction.created_at + INTERVAL '45 minutes'
FROM transaction raffle_transaction
JOIN lucky_number ON lucky_number.transaction_id = raffle_transaction.id
GROUP BY raffle_transaction.external_reference, raffle_transaction.created_at;

INSERT INTO capacity_reservation (external_reference, quantity, status, expires_at)
SELECT
    raffle_transaction.external_reference,
    raffle_transaction.quantity,
    'EXPIRED',
    raffle_transaction.created_at + INTERVAL '45 minutes'
FROM transaction raffle_transaction
WHERE raffle_transaction.status = 'PENDING'
  AND NOT EXISTS (
      SELECT 1
      FROM capacity_reservation reservation
      WHERE reservation.external_reference = raffle_transaction.external_reference
  );

CREATE INDEX idx_capacity_reservation_active_expiration
    ON capacity_reservation (expires_at)
    WHERE status = 'ACTIVE';

CREATE TRIGGER trg_capacity_reservation_updated_at
    BEFORE UPDATE ON capacity_reservation
    FOR EACH ROW
    EXECUTE FUNCTION set_transaction_updated_at();
