CREATE TABLE purchase_intent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(64) NOT NULL,
    action VARCHAR(40) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    external_reference VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    response_payload TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_purchase_intent_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uq_purchase_intent_external_reference UNIQUE (external_reference),
    CONSTRAINT chk_purchase_intent_action
        CHECK (action IN ('MERCADO_PAGO_CHECKOUT', 'CASH_REGISTRATION')),
    CONSTRAINT chk_purchase_intent_status
        CHECK (status IN ('PENDING', 'COMPLETED')),
    CONSTRAINT chk_purchase_intent_request_hash
        CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_purchase_intent_response
        CHECK (
            (status = 'PENDING' AND response_payload IS NULL)
            OR (status = 'COMPLETED' AND response_payload IS NOT NULL)
        ),
    CONSTRAINT fk_purchase_intent_transaction
        FOREIGN KEY (external_reference)
        REFERENCES transaction (external_reference)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TRIGGER trg_purchase_intent_updated_at
    BEFORE UPDATE ON purchase_intent
    FOR EACH ROW
    EXECUTE FUNCTION set_transaction_updated_at();
