ALTER TABLE transaction
    ADD COLUMN mp_collector_id VARCHAR(255),
    ADD COLUMN payment_state_updated_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN payment_state_priority SMALLINT,
    ADD COLUMN current_payment_event_id BIGINT;

UPDATE transaction
SET mp_collector_id = split_part(mp_preference_id, '-', 1)
WHERE payment_method = 'MERCADO_PAGO'
  AND mp_preference_id ~ '^[0-9]+-';

CREATE TABLE provider_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(40) NOT NULL,
    provider_payment_id VARCHAR(255) NOT NULL,
    transaction_id BIGINT,
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_provider_payment_identity UNIQUE (provider, provider_payment_id),
    CONSTRAINT chk_provider_payment_provider CHECK (provider IN ('MERCADO_PAGO')),
    CONSTRAINT fk_provider_payment_transaction
        FOREIGN KEY (transaction_id)
        REFERENCES transaction (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_provider_payment_transaction_id
    ON provider_payment (transaction_id);

CREATE TABLE payment_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_payment_id BIGINT NOT NULL,
    event_key VARCHAR(128) NOT NULL,
    requested_payment_id VARCHAR(255),
    provider_status VARCHAR(40),
    status_detail VARCHAR(100),
    external_reference VARCHAR(255),
    order_external_reference VARCHAR(255),
    preference_id VARCHAR(255),
    collector_id VARCHAR(255),
    transaction_amount NUMERIC(19, 2),
    currency_id VARCHAR(3),
    provider_created_at TIMESTAMP WITH TIME ZONE,
    provider_updated_at TIMESTAMP WITH TIME ZONE,
    reconciliation_status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    processing_status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    failure_reasons VARCHAR(500),
    delivery_count INTEGER NOT NULL DEFAULT 1,
    first_received_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_received_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_payment_event_key UNIQUE (event_key),
    CONSTRAINT chk_payment_event_reconciliation_status
        CHECK (reconciliation_status IN ('RECEIVED', 'MATCHED', 'MISMATCHED')),
    CONSTRAINT chk_payment_event_processing_status
        CHECK (processing_status IN ('RECEIVED', 'APPLIED', 'OBSOLETE', 'REJECTED')),
    CONSTRAINT chk_payment_event_delivery_count CHECK (delivery_count > 0),
    CONSTRAINT fk_payment_event_provider_payment
        FOREIGN KEY (provider_payment_id)
        REFERENCES provider_payment (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_payment_event_history
    ON payment_event (provider_payment_id, provider_updated_at, id);

ALTER TABLE transaction
    ADD CONSTRAINT chk_transaction_payment_state_priority
        CHECK (payment_state_priority IS NULL OR payment_state_priority > 0),
    ADD CONSTRAINT fk_transaction_current_payment_event
        FOREIGN KEY (current_payment_event_id)
        REFERENCES payment_event (id)
        ON DELETE RESTRICT;

INSERT INTO provider_payment (provider, provider_payment_id, transaction_id, first_seen_at)
SELECT 'MERCADO_PAGO', mp_payment_id, id, updated_at
FROM transaction
WHERE payment_method = 'MERCADO_PAGO'
  AND mp_payment_id IS NOT NULL
ON CONFLICT (provider, provider_payment_id) DO NOTHING;

INSERT INTO payment_event (
    provider_payment_id,
    event_key,
    requested_payment_id,
    provider_status,
    external_reference,
    preference_id,
    collector_id,
    transaction_amount,
    currency_id,
    provider_updated_at,
    reconciliation_status,
    processing_status,
    failure_reasons,
    first_received_at,
    last_received_at,
    processed_at
)
SELECT
    provider_payment.id,
    'legacy:' || raffle_transaction.id,
    raffle_transaction.mp_payment_id,
    lower(raffle_transaction.status::TEXT),
    raffle_transaction.external_reference,
    raffle_transaction.mp_preference_id,
    raffle_transaction.mp_collector_id,
    raffle_transaction.total_amount,
    'BRL',
    raffle_transaction.updated_at,
    'MISMATCHED',
    'REJECTED',
    'LEGACY_UNVERIFIED',
    raffle_transaction.updated_at,
    raffle_transaction.updated_at,
    raffle_transaction.updated_at
FROM transaction raffle_transaction
JOIN provider_payment
  ON provider_payment.provider = 'MERCADO_PAGO'
 AND provider_payment.provider_payment_id = raffle_transaction.mp_payment_id
WHERE raffle_transaction.payment_method = 'MERCADO_PAGO'
  AND raffle_transaction.mp_payment_id IS NOT NULL
ON CONFLICT (event_key) DO NOTHING;
