CREATE TABLE raffle_combo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INTEGER NOT NULL,
    price NUMERIC(19, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL,
    highlight_most_chosen BOOLEAN NOT NULL DEFAULT FALSE,
    highlight_best_value BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_raffle_combo_quantity UNIQUE (quantity),
    CONSTRAINT chk_raffle_combo_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_raffle_combo_price_positive CHECK (price > 0),
    CONSTRAINT chk_raffle_combo_display_order_non_negative CHECK (display_order >= 0)
);

INSERT INTO raffle_combo (
    quantity,
    price,
    active,
    display_order,
    highlight_most_chosen,
    highlight_best_value
)
VALUES
    (5, 240.00, TRUE, 1, FALSE, FALSE),
    (10, 460.00, TRUE, 2, FALSE, FALSE),
    (20, 880.00, TRUE, 3, TRUE, FALSE),
    (30, 1275.00, TRUE, 4, FALSE, TRUE);

ALTER TABLE transaction
    ADD COLUMN raffle_combo_id BIGINT,
    ADD CONSTRAINT fk_transaction_raffle_combo
        FOREIGN KEY (raffle_combo_id)
        REFERENCES raffle_combo (id)
        ON DELETE RESTRICT;

ALTER TABLE purchase_intent
    ADD COLUMN raffle_combo_id BIGINT,
    ADD CONSTRAINT fk_purchase_intent_raffle_combo
        FOREIGN KEY (raffle_combo_id)
        REFERENCES raffle_combo (id)
        ON DELETE RESTRICT;
