import twemoji from 'twemoji';

const flagAssetModules = import.meta.glob<string>(
  [
    '/node_modules/@twemoji/svg/1f1e6-1f1e9.svg',
    '/node_modules/@twemoji/svg/1f1e6-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1e6-1f1eb.svg',
    '/node_modules/@twemoji/svg/1f1e6-1f1ec.svg',
    '/node_modules/@twemoji/svg/1f1e6-1f1f1.svg',
    '/node_modules/@twemoji/svg/1f1e6-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1e6-1f1f4.svg',
    '/node_modules/@twemoji/svg/1f1e6-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1e6-1f1f9.svg',
    '/node_modules/@twemoji/svg/1f1e6-1f1fa.svg',
    '/node_modules/@twemoji/svg/1f1e6-1f1ff.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1e7.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1e9.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1eb.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1ec.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1ed.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1ee.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1ef.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1f3.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1f4.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1f8.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1f9.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1fc.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1fe.svg',
    '/node_modules/@twemoji/svg/1f1e7-1f1ff.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1e9.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1eb.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1ec.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1ed.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1ee.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1f1.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1f3.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1f4.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1fa.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1fb.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1fe.svg',
    '/node_modules/@twemoji/svg/1f1e8-1f1ff.svg',
    '/node_modules/@twemoji/svg/1f1e9-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1e9-1f1ef.svg',
    '/node_modules/@twemoji/svg/1f1e9-1f1f0.svg',
    '/node_modules/@twemoji/svg/1f1e9-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1e9-1f1f4.svg',
    '/node_modules/@twemoji/svg/1f1e9-1f1ff.svg',
    '/node_modules/@twemoji/svg/1f1ea-1f1e8.svg',
    '/node_modules/@twemoji/svg/1f1ea-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1ea-1f1ec.svg',
    '/node_modules/@twemoji/svg/1f1ea-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1ea-1f1f8.svg',
    '/node_modules/@twemoji/svg/1f1ea-1f1f9.svg',
    '/node_modules/@twemoji/svg/1f1eb-1f1ee.svg',
    '/node_modules/@twemoji/svg/1f1eb-1f1ef.svg',
    '/node_modules/@twemoji/svg/1f1eb-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1eb-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1e7.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1e9.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1ed.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1f3.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1f6.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1f9.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1fc.svg',
    '/node_modules/@twemoji/svg/1f1ec-1f1fe.svg',
    '/node_modules/@twemoji/svg/1f1ed-1f1f3.svg',
    '/node_modules/@twemoji/svg/1f1ed-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1ed-1f1f9.svg',
    '/node_modules/@twemoji/svg/1f1ed-1f1fa.svg',
    '/node_modules/@twemoji/svg/1f1ee-1f1e9.svg',
    '/node_modules/@twemoji/svg/1f1ee-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1ee-1f1f1.svg',
    '/node_modules/@twemoji/svg/1f1ee-1f1f3.svg',
    '/node_modules/@twemoji/svg/1f1ee-1f1f6.svg',
    '/node_modules/@twemoji/svg/1f1ee-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1ee-1f1f8.svg',
    '/node_modules/@twemoji/svg/1f1ee-1f1f9.svg',
    '/node_modules/@twemoji/svg/1f1ef-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1ef-1f1f4.svg',
    '/node_modules/@twemoji/svg/1f1ef-1f1f5.svg',
    '/node_modules/@twemoji/svg/1f1f0-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1f0-1f1ec.svg',
    '/node_modules/@twemoji/svg/1f1f0-1f1ed.svg',
    '/node_modules/@twemoji/svg/1f1f0-1f1ee.svg',
    '/node_modules/@twemoji/svg/1f1f0-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1f0-1f1f3.svg',
    '/node_modules/@twemoji/svg/1f1f0-1f1f5.svg',
    '/node_modules/@twemoji/svg/1f1f0-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1f0-1f1fc.svg',
    '/node_modules/@twemoji/svg/1f1f0-1f1ff.svg',
    '/node_modules/@twemoji/svg/1f1f1-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1f1-1f1e7.svg',
    '/node_modules/@twemoji/svg/1f1f1-1f1e8.svg',
    '/node_modules/@twemoji/svg/1f1f1-1f1ee.svg',
    '/node_modules/@twemoji/svg/1f1f1-1f1f0.svg',
    '/node_modules/@twemoji/svg/1f1f1-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1f1-1f1f8.svg',
    '/node_modules/@twemoji/svg/1f1f1-1f1f9.svg',
    '/node_modules/@twemoji/svg/1f1f1-1f1fa.svg',
    '/node_modules/@twemoji/svg/1f1f1-1f1fb.svg',
    '/node_modules/@twemoji/svg/1f1f1-1f1fe.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1e8.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1e9.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1ec.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1ed.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1f0.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1f1.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1f3.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1f9.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1fa.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1fb.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1fc.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1fd.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1fe.svg',
    '/node_modules/@twemoji/svg/1f1f2-1f1ff.svg',
    '/node_modules/@twemoji/svg/1f1f3-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1f3-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1f3-1f1ec.svg',
    '/node_modules/@twemoji/svg/1f1f3-1f1ee.svg',
    '/node_modules/@twemoji/svg/1f1f3-1f1f1.svg',
    '/node_modules/@twemoji/svg/1f1f3-1f1f4.svg',
    '/node_modules/@twemoji/svg/1f1f3-1f1f5.svg',
    '/node_modules/@twemoji/svg/1f1f3-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1f3-1f1ff.svg',
    '/node_modules/@twemoji/svg/1f1f4-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1f5-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1f5-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1f5-1f1ec.svg',
    '/node_modules/@twemoji/svg/1f1f5-1f1ed.svg',
    '/node_modules/@twemoji/svg/1f1f5-1f1f0.svg',
    '/node_modules/@twemoji/svg/1f1f5-1f1f1.svg',
    '/node_modules/@twemoji/svg/1f1f5-1f1f8.svg',
    '/node_modules/@twemoji/svg/1f1f5-1f1f9.svg',
    '/node_modules/@twemoji/svg/1f1f5-1f1fc.svg',
    '/node_modules/@twemoji/svg/1f1f5-1f1fe.svg',
    '/node_modules/@twemoji/svg/1f1f6-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1f7-1f1f4.svg',
    '/node_modules/@twemoji/svg/1f1f7-1f1f8.svg',
    '/node_modules/@twemoji/svg/1f1f7-1f1fa.svg',
    '/node_modules/@twemoji/svg/1f1f7-1f1fc.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1e7.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1e8.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1e9.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1ec.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1ee.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1f0.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1f1.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1f3.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1f4.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1f8.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1f9.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1fb.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1fe.svg',
    '/node_modules/@twemoji/svg/1f1f8-1f1ff.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1e9.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1ec.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1ed.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1ef.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1f1.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1f3.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1f4.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1f7.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1f9.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1fb.svg',
    '/node_modules/@twemoji/svg/1f1f9-1f1ff.svg',
    '/node_modules/@twemoji/svg/1f1fa-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1fa-1f1ec.svg',
    '/node_modules/@twemoji/svg/1f1fa-1f1f8.svg',
    '/node_modules/@twemoji/svg/1f1fa-1f1fe.svg',
    '/node_modules/@twemoji/svg/1f1fa-1f1ff.svg',
    '/node_modules/@twemoji/svg/1f1fb-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1fb-1f1e8.svg',
    '/node_modules/@twemoji/svg/1f1fb-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1fb-1f1f3.svg',
    '/node_modules/@twemoji/svg/1f1fb-1f1fa.svg',
    '/node_modules/@twemoji/svg/1f1fc-1f1f8.svg',
    '/node_modules/@twemoji/svg/1f1fe-1f1ea.svg',
    '/node_modules/@twemoji/svg/1f1ff-1f1e6.svg',
    '/node_modules/@twemoji/svg/1f1ff-1f1f2.svg',
    '/node_modules/@twemoji/svg/1f1ff-1f1fc.svg',
  ],
  { eager: true, import: 'default', query: '?url' },
);

const flagAssets = Object.fromEntries(
  Object.entries(flagAssetModules).map(([path, assetUrl]) => [
    path.slice(path.lastIndexOf('/') + 1, -'.svg'.length),
    assetUrl,
  ]),
) as Record<string, string>;

const stateFlagAssetModules = import.meta.glob<string>('/src/assets/flags/br-states/br-*.svg', {
  eager: true,
  import: 'default',
  query: '?url',
});

const stateFlagAssets = Object.fromEntries(
  Object.entries(stateFlagAssetModules).map(([path, assetUrl]) => [
    path.slice(path.lastIndexOf('/') + 1, -'.svg'.length).toUpperCase(),
    assetUrl,
  ]),
) as Record<string, string>;

interface FlagEmojiProps {
  className?: string;
  emoji: string;
}

export function FlagEmoji({ className = '', emoji }: FlagEmojiProps) {
  const codePoint = twemoji.convert.toCodePoint(emoji).toLowerCase();
  const assetUrl = stateFlagAssets[emoji.toUpperCase()] ?? flagAssets[codePoint];

  if (!assetUrl) {
    return (
      <span aria-label={emoji} className={className} role="img">
        {emoji}
      </span>
    );
  }

  return (
    <img alt={emoji} className={`object-contain ${className}`} draggable={false} src={assetUrl} />
  );
}
